apiVersion: tests.testkube.io/v1
kind: Script
metadata:
  name: petstore-inventory
  namespace: testkube
spec:
  content: >-
    {
    	"info": {
    		"_postman_id": "4d8f135c-2d20-42d3-b3f9-01a49d1aa75b",
    		"name": "Petstore - Pet Inventories",
    		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    	},
    	"item": [
    		{
    			"name": "Returns pet inventories by status",
    			"request": {
    				"auth": {
    					"type": "apikey",
    					"apikey": [
    						{
    							"key": "key",
    							"value": "api_key",
    							"type": "string"
    						},
    						{
    							"key": "value",
    							"value": "<API Key>",
    							"type": "string"
    						},
    						{
    							"key": "in",
    							"value": "header",
    							"type": "string"
    						}
    					]
    				},
    				"method": "GET",
    				"header": [],
    				"url": {
    					"raw": "{{baseUrl}}/api/store/inventory",
    					"host": [
    						"{{baseUrl}}"
    					],
    					"path": [
    						"api",
    						"store",
    						"inventory"
    					]
    				},
    				"description": "Returns a map of status codes to quantities"
    			},
    			"response": [
    				{
    					"name": "successful operation",
    					"originalRequest": {
    						"method": "GET",
    						"header": [
    							{
    								"description": "Added as a part of security scheme: apikey",
    								"key": "api_key",
    								"value": "<API Key>"
    							}
    						],
    						"url": {
    							"raw": "{{baseUrl}}/api/store/inventory",
    							"host": [
    								"{{baseUrl}}"
    							],
    							"path": [
    								"api",
    								"store",
    								"inventory"
    							]
    						}
    					},
    					"status": "OK",
    					"code": 200,
    					"_postman_previewlanguage": "json",
    					"header": [
    						{
    							"key": "Content-Type",
    							"value": "application/json"
    						}
    					],
    					"cookie": [],
    					"body": "{}"
    				}
    			]
    		}
    	],
    	"event": [
    		{
    			"listen": "prerequest",
    			"script": {
    				"type": "text/javascript",
    				"exec": [
    					""
    				]
    			}
    		},
    		{
    			"listen": "test",
    			"script": {
    				"type": "text/javascript",
    				"exec": [
    					""
    				]
    			}
    		}
    	],
    	"variable": [
    		{
    			"key": "baseUrl",
    			"value": "http://localhost:8001",
    			"type": "string"
    		}
    	]
    }
  type: postman/collection
