---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 8080
  selector:
    app: petstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - ports:
            - containerPort: 8080
          name: service
          image: swaggerapi/petstore:latest
