apiVersion: tests.testkube.io/v1
kind: Script
metadata:
  name: petstore-findpetbyid
  namespace: testkube
spec:
  content: >-
    {
    	"info": {
    		"_postman_id": "f5f535fa-5f27-4811-a7be-a34e8b695757",
    		"name": "Testing Petstore",
    		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    	},
    	"item": [
    		{
    			"name": "Find pet by ID",
    			"request": {
    				"auth": {
    					"type": "noauth"
    				},
    				"method": "GET",
    				"header": [],
    				"url": {
    					"raw": "{{baseUrl}}/api/pet/:petId",
    					"host": [
    						"{{baseUrl}}"
    					],
    					"path": [
    						"api",
    						"pet",
    						":petId"
    					],
    					"variable": [
    						{
    							"key": "petId",
    							"value": "3",
    							"description": "(Required) ID of pet to return"
    						}
    					]
    				},
    				"description": "Returns a single pet"
    			},
    			"response": [
    				{
    					"name": "successful operation",
    					"originalRequest": {
    						"method": "GET",
    						"header": [
    							{
    								"description": "Added as a part of security scheme: apikey",
    								"key": "api_key",
    								"value": "<API Key>"
    							}
    						],
    						"url": {
    							"raw": "{{baseUrl}}/api/pet/:petId",
    							"host": [
    								"{{baseUrl}}"
    							],
    							"path": [
    								"api",
    								"pet",
    								":petId"
    							],
    							"variable": [
    								{
    									"key": "petId",
    									"value": "-86238540",
    									"description": "(Required) ID of pet to return"
    								}
    							]
    						}
    					},
    					"status": "OK",
    					"code": 200,
    					"_postman_previewlanguage": "json",
    					"header": [
    						{
    							"key": "Content-Type",
    							"value": "application/json"
    						}
    					],
    					"cookie": [],
    					"body": "{\n \"name\": \"doggie\",\n \"photoUrls\": [\n  \"co\",\n  \"do laborum\"\n ],\n \"id\": -91209697,\n \"category\": {\n  \"id\": 31098561,\n  \"name\": \"ipsum ut\"\n },\n \"tags\": [\n  {\n   \"id\": 1064403,\n   \"name\": \"voluptate in\"\n  },\n  {\n   \"id\": -100220,\n   \"name\": \"ad Excepteur deserunt culpa\"\n  }\n ],\n \"status\": \"sold\"\n}"
    				},
    				{
    					"name": "Invalid ID supplied",
    					"originalRequest": {
    						"method": "GET",
    						"header": [
    							{
    								"description": "Added as a part of security scheme: apikey",
    								"key": "api_key",
    								"value": "<API Key>"
    							}
    						],
    						"url": {
    							"raw": "{{baseUrl}}/api/pet/:petId",
    							"host": [
    								"{{baseUrl}}"
    							],
    							"path": [
    								"api",
    								"pet",
    								":petId"
    							],
    							"variable": [
    								{
    									"key": "petId",
    									"value": "-86238540",
    									"description": "(Required) ID of pet to return"
    								}
    							]
    						}
    					},
    					"status": "Bad Request",
    					"code": 400,
    					"_postman_previewlanguage": "text",
    					"header": [
    						{
    							"key": "Content-Type",
    							"value": "text/plain"
    						}
    					],
    					"cookie": [],
    					"body": ""
    				},
    				{
    					"name": "Pet not found",
    					"originalRequest": {
    						"method": "GET",
    						"header": [
    							{
    								"description": "Added as a part of security scheme: apikey",
    								"key": "api_key",
    								"value": "<API Key>"
    							}
    						],
    						"url": {
    							"raw": "{{baseUrl}}/api/pet/:petId",
    							"host": [
    								"{{baseUrl}}"
    							],
    							"path": [
    								"api",
    								"pet",
    								":petId"
    							],
    							"variable": [
    								{
    									"key": "petId",
    									"value": "-86238540",
    									"description": "(Required) ID of pet to return"
    								}
    							]
    						}
    					},
    					"status": "Not Found",
    					"code": 404,
    					"_postman_previewlanguage": "text",
    					"header": [
    						{
    							"key": "Content-Type",
    							"value": "text/plain"
    						}
    					],
    					"cookie": [],
    					"body": ""
    				}
    			]
    		}
    	],
    	"event": [
    		{
    			"listen": "prerequest",
    			"script": {
    				"type": "text/javascript",
    				"exec": [
    					""
    				]
    			}
    		},
    		{
    			"listen": "test",
    			"script": {
    				"type": "text/javascript",
    				"exec": [
    					""
    				]
    			}
    		}
    	],
    	"variable": [
    		{
    			"key": "baseUrl",
    			"value": "http://10.109.114.168:8001"
    		}
    	]
    }
  type: postman/collection
