name: Run Test on TestKube

on:
  push:
    paths:
      - 'cypress-tests/**'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-on-demo-cluster-gke:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME_DEV }}
          location: ${{ secrets.GKE_ZONE_DEV }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Installing TestKube CLI:
      - name: Install TestKube CLI
        run: |-
          bash < <(curl -sSLf https://kubeshop.github.io/testkube/install.sh )

      # Run TestKube script on a GKE cluster
      - name: Run Test
        run: |-
          kubectl testkube tests start petstore-test -p host=http://10.116.9.4:8001 -p baseUrl=http://10.116.9.4:8001 
